import 'server-only';
import { wrapLanguageModel, customProvider, extractReasoningMiddleware } from 'ai';

import { createOpenRouter } from '@openrouter/ai-sdk-provider';

const middleware = extractReasoningMiddleware({
  tagName: 'think',
});

const middlewareWithStartWithReasoning = extractReasoningMiddleware({
  tagName: 'think',
  startWithReasoning: true,
});

const openrouter = createOpenRouter({
  apiKey: process.env.OPENROUTER_API_KEY,
  headers: {
    'HTTP-Referer': 'https://sciraai.in',
    'X-Title': 'Scira AI',
    'Content-Type': 'application/json',
  },
});

export const scira = customProvider({
  languageModels: {
    'scira-arch-router': openrouter('katanemo/Arch-Router-1.5B:hf-inference'),
    'scira-default': openrouter('x-ai/grok-4-1-fast-non-reasoning'),
    'scira-auto': openrouter('x-ai/grok-4-1-fast-non-reasoning'),
    'scira-sarvam-105b': openrouter('sarvam-ai/sarvam-105b'),
    'scira-grok4.1-fast-thinking': openrouter('x-ai/grok-4-1-fast-reasoning'),
    'scira-ext-1': openrouter('x-ai/grok-4-1-fast-reasoning'),
    'scira-ext-2': openrouter('openai/gpt-5.4'),
    // 'scira-ext-3': openrouter('anthropic/claude-sonnet-4.6'),
    'scira-ext-4': openrouter('@cf/zai-org/glm-4.7-flash'),
    'scira-ext-5': openrouter('moonshotai/kimi-k2.5'),
    'scira-ext-6': openrouter('google/gemini-3.1-pro-preview'),
    'scira-ext-7': openrouter('alibaba/qwen3.5-flash'),
    'scira-ext-8': openrouter('x-ai/grok-4.20-experimental-beta-0304-non-reasoning'),
    'scira-nano': openrouter('llama-3.3-70b-versatile'),
    'scira-name': openrouter('google/gemini-2.5-flash-lite-preview-09-2025'),
    'scira-grok-3-mini': openrouter('x-ai/grok-3-mini'),
    'scira-grok-3': openrouter('x-ai/grok-3'),
    'scira-grok-4': openrouter('x-ai/grok-4'),
    'scira-grok-4.20-experimental-beta-0304': openrouter('x-ai/grok-4.20-non-reasoning-latest'),
    'scira-grok-4.20-experimental-beta-0304-thinking': openrouter('x-ai/grok-4.20-reasoning-latest'),
    'scira-grok-4-fast': openrouter('x-ai/grok-4-fast-non-reasoning'),
    'scira-grok-4-fast-think': openrouter('x-ai/grok-4-fast-reasoning'),
    'scira-code': openrouter('x-ai/grok-code-fast-1'),
    'scira-enhance': openrouter('moonshotai/kimi-k2-instruct-0905'),
    'scira-follow-up': openrouter('google/gemini-2.5-flash-lite-preview-09-2025'),
    'scira-qwen-4b': openrouter('Qwen/Qwen3-4B-Instruct-2507:nscale'),
    'scira-qwen-4b-thinking': wrapLanguageModel({
      model: openrouter('Qwen/Qwen3-4B-Thinking-2507:nscale'),
      middleware: [middlewareWithStartWithReasoning],
    }),
    'scira-gpt-4.1-nano': openrouter('openai/gpt-4.1-nano'),
    'scira-gpt-4.1-mini': openrouter('openai/gpt-4.1-mini'),
    'scira-gpt-4.1': openrouter('openai/gpt-4.1'),
    'scira-gpt-5.1': openrouter('openai/gpt-5.1'),
    'scira-gpt-5.1-thinking': openrouter('openai/gpt-5.1'),
    'scira-gpt-5.2': openrouter('openai/gpt-5.2'),
    'scira-gpt-5.3-chat-latest': openrouter('openai/gpt-5.3-chat-latest'),
    'scira-gpt-5.4': openrouter('openai/gpt-5.4'),
    'scira-gpt-5.4-mini': openrouter('openai/gpt-5.4-mini'),
    'scira-gpt-5.4-nano': openrouter('openai/gpt-5.4-nano'),
    'scira-gpt-5.4-thinking': openrouter('openai/gpt-5.4'),
    'scira-gpt-5.4-thinking-xhigh': openrouter('openai/gpt-5.4'),
    'scira-gpt-5.2-thinking': openrouter('openai/gpt-5.2'),
    'scira-gpt-5.2-thinking-xhigh': openrouter('openai/gpt-5.2'),
    'scira-gpt-5.1-codex': openrouter('openai/gpt-5.1-codex'),
    'scira-gpt-5.1-codex-mini': openrouter('openai/gpt-5.1-codex-mini'),
    'scira-gpt-5.1-codex-max': openrouter('openai/gpt-5.1-codex-max'),
    'scira-gpt-5.2-codex': openrouter('openai/gpt-5.2-codex'),
    'scira-gpt-5.3-codex': openrouter('openai/gpt-5.3-codex'),
    'scira-gpt5': openrouter('openai/gpt-5'),
    'scira-gpt5-medium': openrouter('openai/gpt-5'),
    'scira-gpt5-mini': openrouter('openai/gpt-5-mini'),
    'scira-gpt5-nano': openrouter('openai/gpt-5-nano'),
    'scira-o3': openrouter('openai/o3'),
    'scira-o4-mini': openrouter('openai/o4-mini'),
    'scira-gpt5-codex': openrouter('openai/gpt-5-codex'),
    'scira-qwen-32b': wrapLanguageModel({
      model: openrouter('qwen/qwen3-32b'),
      middleware,
    }),
    'scira-qwen-32b-thinking': wrapLanguageModel({
      model: openrouter('qwen/qwen3-32b'),
      middleware,
    }),
    'scira-gpt-oss-20': wrapLanguageModel({
      model: openrouter('openai/gpt-oss-20b'),
      middleware,
    }),
    'scira-nemotron-3-super': openrouter('@cf/nvidia/nemotron-3-120b-a12b'),
    'scira-gpt-oss-120': wrapLanguageModel({
      model: openrouter('openai/gpt-oss-120b'),
      middleware,
    }),
    'scira-trinity-mini': wrapLanguageModel({
      model: openrouter('arcee-ai/trinity-mini'),
      middleware,
    }),
    'scira-trinity-large': wrapLanguageModel({
      model: openrouter('arcee-ai/trinity-large-preview:free'),
      middleware,
    }),
    'scira-step-3.5-flash': openrouter('stepfun/step-3.5-flash:free'),
    'scira-kat-coder': openrouter('kwaipilot/kat-coder-pro-v1'),
    'scira-deepseek-v3': openrouter('deepseek-ai/DeepSeek-V3-0324'),
    'scira-deepseek-v3.1-terminus': openrouter('deepseek/deepseek-v3.1-terminus'),
    'scira-deepseek-chat': openrouter('deepseek/deepseek-v3.2'),
    'scira-deepseek-chat-think': openrouter('deepseek/deepseek-v3.2-thinking'),
    'scira-deepseek-chat-exp': openrouter('deepseek/deepseek-v3.2-exp'),
    'scira-deepseek-chat-think-exp': wrapLanguageModel({
      model: openrouter('deepseek/deepseek-v3.2-exp'),
      middleware,
    }),
    'scira-v0-10': openrouter('vercel/v0-1.0-md'),
    'scira-v0-15': openrouter('vercel/v0-1.5-md'),
    'scira-deepseek-r1': wrapLanguageModel({
      model: openrouter('deepseek/deepseek-r1-turbo'),
      middleware,
    }),
    'scira-deepseek-r1-0528': wrapLanguageModel({
      model: openrouter('deepseek/deepseek-r1-0528'),
      middleware,
    }),
    'scira-qwen-coder-small': openrouter('alibaba/qwen3-coder-30b-a3b'),
    'scira-qwen-coder': openrouter('Qwen/Qwen3-Coder-480B-A35B-Instruct'),
    'scira-qwen-coder-plus': openrouter('alibaba/qwen3-coder-plus'),
    'scira-qwen-coder-next': openrouter('qwen/qwen3-coder-next'),
    'scira-qwen-30': openrouter('Qwen/Qwen3-30B-A3B-Instruct-2507:nebius'),
    'scira-qwen-30-think': wrapLanguageModel({
      model: openrouter('Qwen/Qwen3-30B-A3B-Thinking-2507:nebius'),
      middleware,
    }),
    'scira-qwen-3-vl-30b': openrouter('qwen/qwen3-vl-30b-a3b-instruct'),
    'scira-qwen-3-vl-30b-thinking': wrapLanguageModel({
      model: openrouter('qwen/qwen3-vl-30b-a3b-thinking'),
      middleware,
    }),
    'scira-qwen-3-next': openrouter('Qwen/Qwen3-Next-80B-A3B-Instruct:hyperbolic'),
    'scira-qwen-3-next-think': wrapLanguageModel({
      model: openrouter('Qwen/Qwen3-Next-80B-A3B-Thinking:hyperbolic'),
      middleware: [middlewareWithStartWithReasoning],
    }),
    'scira-qwen-3-max': openrouter('alibaba/qwen3-max'),
    'scira-qwen-3-max-preview': openrouter('alibaba/qwen3-max-preview'),
    'scira-qwen-3-max-preview-thinking': openrouter('alibaba/qwen3-max-thinking'),
    'scira-qwen-235': openrouter('alibaba/qwen-3-235b'),
    'scira-qwen-235-think': wrapLanguageModel({
      model: openrouter('Qwen/Qwen3-235B-A22B-Thinking-2507:fireworks-ai'),
      middleware: [middlewareWithStartWithReasoning],
    }),
    'scira-qwen-3.5-27b': openrouter('qwen/qwen3.5-27b'),
    'scira-qwen-3.5-35b': openrouter('qwen/qwen3.5-35b-a3b'),
    'scira-qwen-3.5-122b': openrouter('qwen/qwen3.5-122b-a10b'),
    'scira-qwen-3.5': openrouter('qwen/qwen3.5-397b-a17b'),
    'scira-qwen-3.5-plus': openrouter('alibaba/qwen3.5-plus'),
    'scira-qwen-3.5-flash': openrouter('alibaba/qwen3.5-flash'),
    'scira-qwen-3-vl': openrouter('alibaba/qwen3-vl-instruct'),
    'scira-qwen-3-vl-thinking': wrapLanguageModel({
      model: openrouter('alibaba/qwen3-vl-thinking'),
      middleware,
    }),
    'scira-glm-air': openrouter('zai/glm-4.5-air'),
    'scira-glm': wrapLanguageModel({
      model: openrouter('zai/glm-4.5'),
      middleware,
    }),
    'scira-glm-4.6': wrapLanguageModel({
      model: openrouter('zai-org/GLM-4.6:zai-org'),
      middleware,
    }),
    'scira-glm-4.6v-flash': wrapLanguageModel({
      model: openrouter('zai-org/GLM-4.6V-Flash:zai-org'),
      middleware,
    }),
    'scira-glm-4.6v': wrapLanguageModel({
      model: openrouter('zai-org/GLM-4.6V:zai-org'),
      middleware,
    }),
    'scira-glm-4.7': wrapLanguageModel({
      model: openrouter('zai-org/GLM-4.7:novita'),
      middleware,
    }),
    'scira-glm-4.7-flash': openrouter('zai-org/glm-4.7-flash'),
    'scira-glm-5': wrapLanguageModel({
      model: openrouter('z-ai/glm-5-turbo'),
      middleware,
    }),
    'scira-glm-5-thinking': wrapLanguageModel({
      model: openrouter('z-ai/glm-5-turbo'),
      middleware,
    }),
    'scira-minimax': wrapLanguageModel({
      model: openrouter('minimaxai/minimax-m1-80k'),
      middleware,
    }),
    'scira-minimax-m2': wrapLanguageModel({
      model: openrouter('minimax/minimax-m2'),
      middleware,
    }),
    'scira-minimax-m2.1': wrapLanguageModel({
      model: openrouter('minimax/minimax-m2.1'),
      middleware,
    }),
    'scira-minimax-m2.1-lightning': wrapLanguageModel({
      model: openrouter('minimax/minimax-m2.1-lightning'),
      middleware,
    }),
    'scira-minimax-m2.7': wrapLanguageModel({
      model: openrouter('minimax/MiniMax-M2.7-highspeed'),
      middleware,
    }),
    'scira-minimax-m2.5': openrouter('MiniMaxAI/MiniMax-M2.5'),
    'scira-cmd-a': openrouter('cohere/command-a-03-2025'),
    'scira-cmd-a-think': openrouter('cohere/command-a-reasoning-08-2025'),
    'scira-kimi-k2-v2': openrouter('moonshotai/kimi-k2-instruct-0905'),
    'scira-kimi-k2-v2-thinking': wrapLanguageModel({
      model: openrouter('moonshotai/kimi-k2-thinking-turbo'),
      middleware,
    }),
    'scira-kimi-k2.5': openrouter('moonshotai/Kimi-K2.5'),
    'scira-kimi-k2.5-thinking': openrouter('moonshotai/kimi-k2.5'),
    'scira-ministral-3b': openrouter('mistralai/ministral-3b-2512'),
    'scira-ministral-8b': openrouter('mistralai/ministral-8b-2512'),
    'scira-ministral-14b': openrouter('mistralai/ministral-14b-2512'),
    'scira-mistral-large': openrouter('mistralai/mistral-large-2512'),
    'scira-mistral-medium': openrouter('mistralai/mistral-medium-2508'),
    'scira-magistral-small': openrouter('mistralai/magistral-small-2509'),
    'scira-magistral-medium': openrouter('mistralai/magistral-medium-2509'),
    'scira-mistral-small': openrouter('mistralai/mistral-small-2603'),
    'scira-mistral-small-think': openrouter('mistralai/mistral-small-2603'),
    'scira-leanstral': openrouter('mistralai/labs-leanstral-2603'),
    'scira-devstral': openrouter('mistralai/devstral-2512'),
    'scira-devstral-small': openrouter('mistralai/labs-devstral-small-2512'),
    'scira-google-lite': openrouter('google/gemini-flash-lite-latest'),
    'scira-google': openrouter('google/gemini-flash-latest'),
    'scira-google-think': openrouter('google/gemini-flash-latest'),
    'scira-google-pro': openrouter('google/gemini-2.5-pro'),
    'scira-google-pro-think': openrouter('google/gemini-2.5-pro'),
    'scira-gemini-3-flash': openrouter('google/gemini-3-flash-preview'),
    'scira-gemini-3-flash-think': openrouter('google/gemini-3-flash-preview'),
    'scira-gemini-3.1-flash-lite': openrouter('google/gemini-3.1-flash-lite-preview'),
    'scira-gemini-3.1-flash-lite-think': openrouter('google/gemini-3.1-flash-lite-preview'),
    'scira-gemini-3.1-pro': openrouter('google/gemini-3.1-pro-preview'),
    'scira-anthropic-small': openrouter('anthropic/claude-haiku-4-5'),
    'scira-anthropic': openrouter('anthropic/claude-sonnet-4-5'),
    'scira-anthropic-think': openrouter('anthropic/claude-sonnet-4-5'),
    'scira-anthropic-sonnet-4.6': openrouter('anthropic/claude-sonnet-4-6'),
    'scira-anthropic-sonnet-4.6-think': openrouter('anthropic/claude-sonnet-4-6'),
    'scira-mimo-v2-flash': wrapLanguageModel({
      model: openrouter('xiaomi/mimo-v2-flash'),
      middleware,
    }),
    'scira-mimo-v2-pro': wrapLanguageModel({
      model: openrouter('xiaomi/mimo-v2-pro'),
      middleware,
    }),
    'scira-anthropic-opus': openrouter('anthropic/claude-opus-4-5'),
    'scira-anthropic-opus-think': openrouter('anthropic/claude-opus-4-5'),
    'scira-anthropic-opus-4.6': openrouter('anthropic/claude-opus-4-6'),
    'scira-anthropic-opus-4.6-think': openrouter('anthropic/claude-opus-4-6'),
    'scira-nova-2-lite': openrouter('amazon/nova-2-lite'),
    'scira-seed-1.6': wrapLanguageModel({
      model: ark('seed-1-6-250915'),
      middleware,
    }),
    'scira-seed-1.8': wrapLanguageModel({
      model: ark('seed-1-8-251228'),
      middleware,
    }),
    'scira-seed-2.0-mini': wrapLanguageModel({
      model: ark('seed-2-0-mini-260215'),
      middleware,
    }),
    'scira-seed-2.0-lite': ark('seed-2-0-lite-260228'),
    'scira-seed-1.6-flash': wrapLanguageModel({
      model: ark('seed-1-6-flash-250715'),
      middleware,
    }),
    'scira-mercury-2': openrouter('inception/mercury-2'),
  },
});

// Re-export all model data and pure helpers from the client-safe models module
export type { ModelProvider, ProviderInfo, Model } from './models';
export {
  PROVIDERS,
  models,
  getModelConfig,
  requiresAuthentication,
  requiresProSubscription,
  requiresMaxSubscription,
  isFreeUnlimited,
  hasVisionSupport,
  hasPdfSupport,
  hasReasoningSupport,
  isExperimentalModel,
  getMaxOutputTokens,
  getModelParameters,
  canUseModel,
  shouldBypassRateLimits,
  getAcceptedFileTypes,
  supportsExtremeMode,
  getExtremeModels,
  supportsCanvasMode,
  isModelRestrictedInRegion,
  getFilteredModels,
  authRequiredModels,
  proRequiredModels,
  freeUnlimitedModels,
  getModelProvider,
  getModelProviderInfo,
  getActiveProviders,
  getModelsByProvider,
} from './models';
